name: shopping_list_example
description: "Shopping list application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  go_router: ^14.2.1
  path_provider: ^2.1.3
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  multiple_localization: ^0.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  intl_translation: ^0.20.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

alex:
  l10n:
    base_locale_for_xml: ru
    xml_output_dir: lib/application/l10n/translations
    translation_files_pattern: intl_{locale}.arb
    source_file: lib/application/localizations.dart
    output_dir: lib/application/l10n